path_css = {'phone':r'html.asp-ws.a-ember.a-transition.a-transform.a-opacity.a-border-image.a-border-radius.a-box-shadow.a-text-stroke.a-text-shadow.a-touch-scrolling.a-transform3d.a-gradients.a-local-storage.a-textarea-placeholder.a-input-placeholder.a-autofocus.a-webworker.a-history.a-geolocation.a-drag-drop.a-svg.a-canvas.a-video.a-audio.a-js.a-ws.asp-js.asp-audio.asp-video.asp-canvas.asp-drag-drop.asp-geolocation.asp-history.asp-autofocus.asp-input-placeholder.asp-textarea-placeholder.asp-local-storage.asp-gradients.asp-transform3d.asp-touch-scrolling.asp-text-shadow.asp-text-stroke.asp-box-shadow.asp-border-radius.asp-border-image.asp-opacity.asp-transform.asp-transition body.a-aui_157141-c.a-aui_72554-c.a-aui_dropdown_187959-c.a-aui_pci_risk_banner_210084-c.a-aui_perf_130093-c.a-aui_tnr_v2_180836-c.a-aui_ux_145937-c.a-meter-animate div#a-page div#sc-content-container div#MYO-app div.a-container.no-top-padding div.a-row.a-spacing-medium div.a-column.a-span10 div.a-section.a-spacing-medium.a-spacing-top-extra-large div.a-row.a-spacing-small.a-spacing-top-small div.a-column.a-span5.a-span-last div div.a-box div.a-box-inner div.a-row div div.a-column.a-span6.a-span-last table.a-normal.a-spacing-block tbody tr td.a-color-.a-text-left.a-align-bottom span span',
            'buyer_info':r'html.asp-ws.a-ember.a-transition.a-transform.a-opacity.a-border-image.a-border-radius.a-box-shadow.a-text-stroke.a-text-shadow.a-touch-scrolling.a-transform3d.a-gradients.a-local-storage.a-textarea-placeholder.a-input-placeholder.a-autofocus.a-webworker.a-history.a-geolocation.a-drag-drop.a-svg.a-canvas.a-video.a-audio.a-js.a-ws.asp-js.asp-audio.asp-video.asp-canvas.asp-drag-drop.asp-geolocation.asp-history.asp-autofocus.asp-input-placeholder.asp-textarea-placeholder.asp-local-storage.asp-gradients.asp-transform3d.asp-touch-scrolling.asp-text-shadow.asp-text-stroke.asp-box-shadow.asp-border-radius.asp-border-image.asp-opacity.asp-transform.asp-transition body.a-aui_157141-c.a-aui_72554-c.a-aui_dropdown_187959-c.a-aui_pci_risk_banner_210084-c.a-aui_perf_130093-c.a-aui_tnr_v2_180836-c.a-aui_ux_145937-c.a-meter-animate div#a-page div#sc-content-container div#MYO-app div.a-container.no-top-padding div.a-row.a-spacing-medium div.a-column.a-span10 div.a-section.a-spacing-medium.a-spacing-top-extra-large div.a-row.a-spacing-small.a-spacing-top-small div.a-column.a-span5.a-span-last div div.a-box div.a-box-inner div.a-row div.a-column.a-span6 table.a-normal tbody tr td span span div div',
            'product_name':r'.a-transition.a-transform.a-opacity.a-border-image.a-border-radius.a-box-shadow.a-text-stroke.a-text-shadow.a-touch-scrolling.a-transform3d.a-gradients.a-local-storage.a-textarea-placeholder.a-input-placeholder.a-autofocus.a-webworker.a-history.a-geolocation.a-drag-drop.a-svg.a-canvas.a-video.a-audio.a-js.a-ws.asp-js.asp-audio.asp-video.asp-canvas.asp-drag-drop.asp-geolocation.asp-history.asp-autofocus.asp-input-placeholder.asp-textarea-placeholder.asp-local-storage.asp-gradients.asp-transform3d.asp-touch-scrolling.asp-text-shadow.asp-text-stroke.asp-box-shadow.asp-border-radius.asp-border-image.asp-opacity.asp-transform.asp-transition body.a-aui_157141-c.a-aui_72554-c.a-aui_dropdown_187959-c.a-aui_pci_risk_banner_210084-c.a-aui_perf_130093-c.a-aui_tnr_v2_180836-c.a-aui_ux_145937-c.a-meter-animate div#a-page div#sc-content-container div#MYO-app div.a-container.no-top-padding div.a-row.a-spacing-medium div.a-column.a-span10 div.a-section.a-spacing-medium.a-spacing-top-extra-large div.a-row.a-spacing-medium.a-spacing-top-medium div div.a-section div.a-section.a-spacing-top-base div table.a-keyvalue tbody tr td div.myo-list-orders-product-name-cell div div a div.more-info-column-word-wrap-break-word',
            'SKU':r'html.asp-ws.a-ember.a-transition.a-transform.a-opacity.a-border-image.a-border-radius.a-box-shadow.a-text-stroke.a-text-shadow.a-touch-scrolling.a-transform3d.a-gradients.a-local-storage.a-textarea-placeholder.a-input-placeholder.a-autofocus.a-webworker.a-history.a-geolocation.a-drag-drop.a-svg.a-canvas.a-video.a-audio.a-js.a-ws.asp-js.asp-audio.asp-video.asp-canvas.asp-drag-drop.asp-geolocation.asp-history.asp-autofocus.asp-input-placeholder.asp-textarea-placeholder.asp-local-storage.asp-gradients.asp-transform3d.asp-touch-scrolling.asp-text-shadow.asp-text-stroke.asp-box-shadow.asp-border-radius.asp-border-image.asp-opacity.asp-transform.asp-transition body.a-aui_157141-c.a-aui_72554-c.a-aui_dropdown_187959-c.a-aui_pci_risk_banner_210084-c.a-aui_perf_130093-c.a-aui_tnr_v2_180836-c.a-aui_ux_145937-c.a-meter-animate div#a-page div#sc-content-container div#MYO-app div.a-container.no-top-padding div.a-row.a-spacing-medium div.a-column.a-span10 div.a-section.a-spacing-medium.a-spacing-top-extra-large div.a-row.a-spacing-medium.a-spacing-top-medium div div.a-section div.a-section.a-spacing-top-base div table.a-keyvalue tbody tr td div.myo-list-orders-product-name-cell div.product-name-column-word-wrap-break-all div',
            'order_num':r'html.asp-ws.a-ember.a-transition.a-transform.a-opacity.a-border-image.a-border-radius.a-box-shadow.a-text-stroke.a-text-shadow.a-touch-scrolling.a-transform3d.a-gradients.a-local-storage.a-textarea-placeholder.a-input-placeholder.a-autofocus.a-webworker.a-history.a-geolocation.a-drag-drop.a-svg.a-canvas.a-video.a-audio.a-js.a-ws.asp-js.asp-audio.asp-video.asp-canvas.asp-drag-drop.asp-geolocation.asp-history.asp-autofocus.asp-input-placeholder.asp-textarea-placeholder.asp-local-storage.asp-gradients.asp-transform3d.asp-touch-scrolling.asp-text-shadow.asp-text-stroke.asp-box-shadow.asp-border-radius.asp-border-image.asp-opacity.asp-transform.asp-transition body.a-aui_157141-c.a-aui_72554-c.a-aui_dropdown_187959-c.a-aui_pci_risk_banner_210084-c.a-aui_perf_130093-c.a-aui_tnr_v2_180836-c.a-aui_ux_145937-c.a-meter-animate div#a-page div#sc-content-container div#MYO-app div.a-container.no-top-padding div.a-row.a-spacing-medium div.a-column.a-span10 div.a-section.a-spacing-medium.a-spacing-top-extra-large div div.a-row.a-spacing-mini div.a-column.a-span12 span.a-text-bold',
            'date':r'html.asp-ws.a-ember.a-transition.a-transform.a-opacity.a-border-image.a-border-radius.a-box-shadow.a-text-stroke.a-text-shadow.a-touch-scrolling.a-transform3d.a-gradients.a-local-storage.a-textarea-placeholder.a-input-placeholder.a-autofocus.a-webworker.a-history.a-geolocation.a-drag-drop.a-svg.a-canvas.a-video.a-audio.a-js.a-ws.asp-js.asp-audio.asp-video.asp-canvas.asp-drag-drop.asp-geolocation.asp-history.asp-autofocus.asp-input-placeholder.asp-textarea-placeholder.asp-local-storage.asp-gradients.asp-transform3d.asp-touch-scrolling.asp-text-shadow.asp-text-stroke.asp-box-shadow.asp-border-radius.asp-border-image.asp-opacity.asp-transform.asp-transition body.a-aui_157141-c.a-aui_72554-c.a-aui_dropdown_187959-c.a-aui_pci_risk_banner_210084-c.a-aui_perf_130093-c.a-aui_tnr_v2_180836-c.a-aui_ux_145937-c.a-meter-animate div#a-page div#sc-content-container div#MYO-app div.a-container.no-top-padding div.a-row.a-spacing-medium div.a-column.a-span10 div.a-section.a-spacing-medium.a-spacing-top-extra-large div.a-row.a-spacing-small.a-spacing-top-small div.a-column.a-span7 div div.a-section div.a-box div.a-box-inner div.a-row div.a-column.a-span7 table.a-normal tbody tr td.a-color-.a-text-left.a-align-bottom span',
            'price':r'html.asp-ws.a-ember.a-transition.a-transform.a-opacity.a-border-image.a-border-radius.a-box-shadow.a-text-stroke.a-text-shadow.a-touch-scrolling.a-transform3d.a-gradients.a-local-storage.a-textarea-placeholder.a-input-placeholder.a-autofocus.a-webworker.a-history.a-geolocation.a-drag-drop.a-svg.a-canvas.a-video.a-audio.a-js.a-ws.asp-js.asp-audio.asp-video.asp-canvas.asp-drag-drop.asp-geolocation.asp-history.asp-autofocus.asp-input-placeholder.asp-textarea-placeholder.asp-local-storage.asp-gradients.asp-transform3d.asp-touch-scrolling.asp-text-shadow.asp-text-stroke.asp-box-shadow.asp-border-radius.asp-border-image.asp-opacity.asp-transform.asp-transition body.a-aui_157141-c.a-aui_72554-c.a-aui_dropdown_187959-c.a-aui_pci_risk_banner_210084-c.a-aui_perf_130093-c.a-aui_tnr_v2_180836-c.a-aui_ux_145937-c.a-meter-animate div#a-page div#sc-content-container div#MYO-app div.a-container.no-top-padding div.a-row.a-spacing-medium div.a-column.a-span10 div.a-section.a-spacing-medium.a-spacing-top-extra-large div.a-row.a-spacing-large div table.a-keyvalue tbody tr td.a-text-right span',
            'quantity':r'html.asp-ws.a-ember.a-transition.a-transform.a-opacity.a-border-image.a-border-radius.a-box-shadow.a-text-stroke.a-text-shadow.a-touch-scrolling.a-transform3d.a-gradients.a-local-storage.a-textarea-placeholder.a-input-placeholder.a-autofocus.a-webworker.a-history.a-geolocation.a-drag-drop.a-svg.a-canvas.a-video.a-audio.a-js.a-ws.asp-js.asp-audio.asp-video.asp-canvas.asp-drag-drop.asp-geolocation.asp-history.asp-autofocus.asp-input-placeholder.asp-textarea-placeholder.asp-local-storage.asp-gradients.asp-transform3d.asp-touch-scrolling.asp-text-shadow.asp-text-stroke.asp-box-shadow.asp-border-radius.asp-border-image.asp-opacity.asp-transform.asp-transition body.a-aui_157141-c.a-aui_72554-c.a-aui_dropdown_187959-c.a-aui_pci_risk_banner_210084-c.a-aui_perf_130093-c.a-aui_tnr_v2_180836-c.a-aui_ux_145937-c.a-meter-animate div#a-page div#sc-content-container div#MYO-app div.a-container.no-top-padding div.a-row.a-spacing-medium div.a-column.a-span10 div.a-section.a-spacing-medium.a-spacing-top-extra-large div.a-row.a-spacing-large div table.a-keyvalue tbody tr td',
            'sub_total':r'html.asp-ws.a-ember.a-transition.a-transform.a-opacity.a-border-image.a-border-radius.a-box-shadow.a-text-stroke.a-text-shadow.a-touch-scrolling.a-transform3d.a-gradients.a-local-storage.a-textarea-placeholder.a-input-placeholder.a-autofocus.a-webworker.a-history.a-geolocation.a-drag-drop.a-svg.a-canvas.a-video.a-audio.a-js.a-ws.asp-js.asp-audio.asp-video.asp-canvas.asp-drag-drop.asp-geolocation.asp-history.asp-autofocus.asp-input-placeholder.asp-textarea-placeholder.asp-local-storage.asp-gradients.asp-transform3d.asp-touch-scrolling.asp-text-shadow.asp-text-stroke.asp-box-shadow.asp-border-radius.asp-border-image.asp-opacity.asp-transform.asp-transition body.a-aui_157141-c.a-aui_72554-c.a-aui_dropdown_187959-c.a-aui_pci_risk_banner_210084-c.a-aui_perf_130093-c.a-aui_tnr_v2_180836-c.a-aui_ux_145937-c.a-meter-animate div#a-page div#sc-content-container div#MYO-app div.a-container.no-top-padding div.a-row.a-spacing-medium div.a-column.a-span10 div.a-section.a-spacing-medium.a-spacing-top-extra-large div.a-row.a-spacing-large div table.a-keyvalue tbody tr td div table.a-normal.a-spacing-none tbody div.a-row div.a-column.a-span6.a-text-right.no-right-margin span.a-color-',
            'signature':r'html.asp-ws.a-ember.a-transition.a-transform.a-opacity.a-border-image.a-border-radius.a-box-shadow.a-text-stroke.a-text-shadow.a-touch-scrolling.a-transform3d.a-gradients.a-local-storage.a-textarea-placeholder.a-input-placeholder.a-autofocus.a-webworker.a-history.a-geolocation.a-drag-drop.a-svg.a-canvas.a-video.a-audio.a-js.a-ws.asp-js.asp-audio.asp-video.asp-canvas.asp-drag-drop.asp-geolocation.asp-history.asp-autofocus.asp-input-placeholder.asp-textarea-placeholder.asp-local-storage.asp-gradients.asp-transform3d.asp-touch-scrolling.asp-text-shadow.asp-text-stroke.asp-box-shadow.asp-border-radius.asp-border-image.asp-opacity.asp-transform.asp-transition body.a-aui_157141-c.a-aui_72554-c.a-aui_dropdown_187959-c.a-aui_pci_risk_banner_210084-c.a-aui_perf_130093-c.a-aui_tnr_v2_180836-c.a-aui_ux_145937-c.a-meter-animate div#a-page div#sc-navbar-container div#remote-nav-container div#sc-masthead.clearable div#sc-quick-search-switch div#sc-mkt-switcher.sc-drop-nav div#sc-mkt-switcher-form.sc-mkt-switcher-form div.sc-mkt-picker-switcher-txt.sc-mkt-picker-bold'
            }


path_xpath = {

            'buyer_info': r'//*[@data-test-id="shipping-section-buyer-address"]',
            'product_name': r'//*[@class="more-info-column-word-wrap-break-word"]',
            'SKU': r'//*[@class="product-name-column-word-wrap-break-all"]',
            'order_id': r'//*[@data-test-id="order-id-value"]',
            'date': r'//*[@data-test-id="order-summary-purchase-date-value"]',
            'price': r'//*[@class="a-text-right"]',
            'quantity': r'//*[@class="a-row a-spacing-large"]',
            'sub_total': r'//*[@class="a-row a-spacing-large"]//*[@class="a-color-"]',
            'signature': r'//*[@class="sc-mkt-picker-switcher-txt sc-mkt-picker-bold"]',
            'total': r'//*[@class="a-color- a-text-bold"]',
            'phone': r'//*[@data-test-id="shipping-section-phone"]',
            'refund': r'//*[@class="a-row a-spacing-large"]//*[@class="a-color-state"]'

              }

